# Assignment - 1

Pytorch is an open source machine learning framework that accelerates the path from research prototyping to production deployment.

The 5 tensor operation functions that we are going to look at are:
- torch.add
- torch.ones
- torch.concat
- torch.squeeze
- torch.split

In [3]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.add 

This function adds two tensors.

In [28]:
# Example 1
a = np.array([[1, 2], [3, 4.]])
tensor1 = torch.from_numpy(a)
a = np.array([[5., 6], [7, 8.]])
tensor2 = torch.from_numpy(a)
tensor3 = tensor1.add(tensor2)
tensor3

tensor([[ 6.,  8.],
        [10., 12.]], dtype=torch.float64)

In above example torch adds two distincts tensors of same dimensions using .add() function.

In [29]:
# Example 2
a = np.array([[1, 2], [3, 4.]])
tensor1 = torch.from_numpy(a)
a = np.array([[5., 6], [7, 8.], [9, 10]])
tensor2 = torch.from_numpy(a)
tensor3 = tensor1.add(tensor2)
tensor3

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

Add function can add two tensors of same dimensions.

## Function 2 - torch.ones 

This function torch creates a tensor of 1s of the size given as arguments.

In [7]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In above example torch creates a tensor of 1s of the size given as arguments.

## Function3 - concat
Function concat two tensors.

In [11]:
x = torch.rand(2,3)
concat = torch.cat((x,x))
print(concat)

tensor([[0.3705, 0.9035, 0.9913],
        [0.0333, 0.7780, 0.5208],
        [0.3705, 0.9035, 0.9913],
        [0.0333, 0.7780, 0.5208]])


Concatenates 2 tensors on zeroth dimension

In [12]:
x = torch.rand(2,3)
concat = torch.cat((x,x), dim=1)
print(concat)

tensor([[0.4630, 0.9728, 0.6436, 0.4630, 0.9728, 0.6436],
        [0.8728, 0.4007, 0.3730, 0.8728, 0.4007, 0.3730]])


Concatenates 2 tensors on first dimension

## Function 4 - squeeze and unsqueeze

Squeeze functions reduces one dimension from a tensor.

Unsqueeze function adds a fake dimension without changing the dimension of tensor.

In [26]:
x = torch.rand(3,2,1)
squeezed = x.squeeze()
print(squeezed)

tensor([[0.7968, 0.5550],
        [0.5551, 0.9458],
        [0.5570, 0.9679]])


Removes the 1 sized dimension.

In [27]:
x = torch.rand(3,2)
squeezed = x.squeeze()
print(squeezed)

tensor([[0.9167, 0.5593],
        [0.0624, 0.1613],
        [0.4861, 0.3038]])


Squueze function works on tensors with more than 2 dimensions.

In [21]:
x = torch.rand(3,2)
with_fake_dimension = x.unsqueeze(0)
print(with_fake_dimension)

tensor([[[0.0343, 0.3738],
         [0.6220, 0.9565],
         [0.4851, 0.5131]]])


Added a fake zeroth dimension.

## Function 5 - Split

Add some explanations

In [36]:
x = torch.rand(2,3)
splitted = x.split(split_size=2, dim=1)
print(splitted)

(tensor([[0.3247, 0.1103],
        [0.0619, 0.9436]]), tensor([[0.1492],
        [0.6315]]))


In above example torch splits the tensor into 2 tensors along axis 1.

In [37]:
x = torch.rand(3,3)
splitted = x.split(split_size=2, dim=0)
print(splitted)

(tensor([[0.0721, 0.9892, 0.1211],
        [0.9970, 0.0381, 0.2526]]), tensor([[0.8599, 0.2641, 0.8046]]))


In above example torch splits the tensor into 2 tensors along axis 0.

## Conclusion

In this notebook wecovered the following functions-
- add
- ones
- concat
- squeeze
- split

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
